In [37]:
import pandas as pd
import numpy as np 

from sklearn.metrics import classification_report

In [2]:
# iris_data = pd.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')
df_train = pd.read_csv("avila/avila-tr.txt", sep=",", header=None, names=['Col1', 'Col2', 'Col3', 'Col4', 'Col5', 'Col6', \
                                                  'Col7', 'Col8', 'Col9', 'Col10', 'Label'])
df_train.head()

# iris_data = pd.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')
df_test = pd.read_csv("avila/avila-ts.txt", sep=",", header=None, names=['Col1', 'Col2', 'Col3', 'Col4', 'Col5', 'Col6', \
                                                  'Col7', 'Col8', 'Col9', 'Col10', 'Label'])
df_train.head()

Col1      Col2      Col3      Col4      Col5      Col6      Col7  \
0  0.266074 -0.165620  0.320980  0.483299  0.172340  0.273364  0.371178   
1  0.130292  0.870736 -3.210528  0.062493  0.261718  1.436060  1.465940   
2 -0.116585  0.069915  0.068476 -0.783147  0.261718  0.439463 -0.081827   
3  0.031541  0.297600 -3.210528 -0.583590 -0.721442 -0.307984  0.710932   
4  0.229043  0.807926 -0.052442  0.082634  0.261718  0.148790  0.635431   

       Col8      Col9     Col10 Label  
0  0.929823  0.251173  0.159345     A  
1  0.636203  0.282354  0.515587     A  
2 -0.888236 -0.123005  0.582939     A  
3  1.051693  0.594169 -0.533994     A  
4  0.051062  0.032902 -0.086652     F

In [5]:
df_train['Label'].shape

(10430,)

In [36]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder() 
df_train['Label'] = LE.fit_transform(df_train['Label'])
y_train = df_train['Label']
X_train = df_train.drop(columns=['Label'])
print(X_train[:5]) 

LE = LabelEncoder() 
df_test['Label'] = LE.fit_transform(df_test['Label'])
y_test = df_test['Label']
X_test = df_test.drop(columns=['Label'])
print(X_test[:5],y_test[:5]) 


       Col1      Col2      Col3      Col4      Col5      Col6      Col7  \
0  0.266074 -0.165620  0.320980  0.483299  0.172340  0.273364  0.371178   
1  0.130292  0.870736 -3.210528  0.062493  0.261718  1.436060  1.465940   
2 -0.116585  0.069915  0.068476 -0.783147  0.261718  0.439463 -0.081827   
3  0.031541  0.297600 -3.210528 -0.583590 -0.721442 -0.307984  0.710932   
4  0.229043  0.807926 -0.052442  0.082634  0.261718  0.148790  0.635431   

       Col8      Col9     Col10  
0  0.929823  0.251173  0.159345  
1  0.636203  0.282354  0.515587  
2 -0.888236 -0.123005  0.582939  
3  1.051693  0.594169 -0.533994  
4  0.051062  0.032902 -0.086652  
       Col1      Col2      Col3      Col4      Col5      Col6      Col7  \
0 -3.498799  0.250492  0.232070  1.224178 -4.922215  1.145386  0.182426   
1  0.204355 -0.354049  0.320980  0.410166 -0.989576 -2.218127  0.220177   
2  0.759828 -1.304042 -0.023991 -0.973663 -0.006417 -0.349509 -0.421580   
3 -0.005490  0.360409  0.281860 -0.213479 -1.

In [10]:
# iris.data chứa dữ liệu X 
# print(iris.data.shape) # shape của X 
# print(iris.target.shape) # shape của labels 
# print(iris.data[:10])
# print(iris.feature_names)
# print(iris.target) # có 3 labels: 0, 1, 2
# print(iris.target_names)

In [3]:
# from sklearn.model_selection import train_test_split  
# X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=9)
# print(X_train.shape,y_train.shape)
# print(X_test.shape,y_test.shape)

(8344, 10) (8344,)
(2086, 10) (2086,)


# linear

In [39]:
# ví dụ về sử dụng SVM 
from sklearn import metrics
from sklearn import svm 
svm_classifier = svm.SVC(kernel='linear',gamma=0.01, C=100., max_iter= 200000)
svm_classifier.fit(X_train,y_train)

//anaconda3/envs/nlp/lib/python3.7/site-packages/sklearn/svm/_base.py:231: ConvergenceWarning: Solver terminated early (max_iter=200000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(C=100.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='linear',
    max_iter=200000, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [40]:
# predict
y_pred_svm = svm_classifier.predict(X_test)
print('predict:\n',y_pred_svm)
print(classification_report(y_test,y_pred_svm))

# tính accuracy 
acc_score_svm = metrics.accuracy_score(y_pred_svm,y_test) 
print('accuracy:\n',acc_score_svm) 

predict:
 [ 0 10  8 ...  5  5  5]
              precision    recall  f1-score   support

           0       0.57      0.29      0.38      4286
           1       1.00      1.00      1.00         5
           2       0.00      0.00      0.00       103
           3       0.00      0.00      0.00       353
           4       0.50      0.56      0.53      1095
           5       0.30      0.80      0.44      1962
           6       0.54      0.10      0.17       447
           7       0.64      0.37      0.47       520
           8       0.89      0.88      0.88       832
           9       0.00      0.00      0.00        45
          10       0.85      0.66      0.74       522
          11       0.72      0.67      0.69       267

    accuracy                           0.47     10437
   macro avg       0.50      0.44      0.44     10437
weighted avg       0.53      0.47      0.45     10437

accuracy:
 0.4704416978058829


//anaconda3/envs/nlp/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# sigmoid

In [41]:
# ví dụ về sử dụng SVM 
from sklearn import metrics
from sklearn import svm 
svm_classifier = svm.SVC(kernel='sigmoid',gamma=0.001, C=1000., max_iter= 2000000)
svm_classifier.fit(X_train,y_train)
# predict
y_pred_svm = svm_classifier.predict(X_test)
print('predict:\n',y_pred_svm)
print(classification_report(y_test,y_pred_svm))

# tính accuracy 
acc_score_svm = metrics.accuracy_score(y_pred_svm,y_test) 
print('accuracy:\n',acc_score_svm) 

predict:
 [0 8 8 ... 0 0 5]
              precision    recall  f1-score   support

           0       0.50      0.72      0.59      4286
           1       0.31      1.00      0.48         5
           2       0.00      0.00      0.00       103
           3       0.00      0.00      0.00       353
           4       0.51      0.29      0.37      1095
           5       0.37      0.41      0.39      1962
           6       0.00      0.00      0.00       447
           7       0.54      0.18      0.27       520
           8       0.88      0.82      0.85       832
           9       0.00      0.00      0.00        45
          10       0.73      0.56      0.63       522
          11       0.73      0.51      0.60       267

    accuracy                           0.52     10437
   macro avg       0.38      0.37      0.35     10437
weighted avg       0.48      0.52      0.48     10437

accuracy:
 0.5171026156941649


//anaconda3/envs/nlp/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# rbf

In [42]:
# ví dụ về sử dụng SVM 
from sklearn import metrics
from sklearn import svm 
svm_classifier = svm.SVC(kernel='rbf',gamma=0.001, C=1000., max_iter= 2000000)
svm_classifier.fit(X_train,y_train)
# predict
y_pred_svm = svm_classifier.predict(X_test)
print('predict:\n',y_pred_svm)
print(classification_report(y_test,y_pred_svm))

# tính accuracy 
acc_score_svm = metrics.accuracy_score(y_pred_svm,y_test) 
print('accuracy:\n',acc_score_svm) 

predict:
 [ 9 10  0 ...  0  0  0]
              precision    recall  f1-score   support

           0       0.59      0.95      0.73      4286
           1       1.00      1.00      1.00         5
           2       1.00      0.04      0.07       103
           3       0.75      0.03      0.05       353
           4       0.67      0.62      0.64      1095
           5       0.60      0.06      0.11      1962
           6       0.57      0.41      0.48       447
           7       0.71      0.46      0.56       520
           8       0.98      0.97      0.98       832
           9       1.00      0.64      0.78        45
          10       0.90      0.82      0.86       522
          11       0.83      0.81      0.82       267

    accuracy                           0.65     10437
   macro avg       0.80      0.57      0.59     10437
weighted avg       0.67      0.65      0.58     10437

accuracy:
 0.6514324039474945


# poly

In [43]:
# ví dụ về sử dụng SVM 
from sklearn import metrics
from sklearn import svm 
svm_classifier = svm.SVC(kernel='poly',gamma=0.001, C=100., max_iter= 2000000)
svm_classifier.fit(X_train,y_train)
# predict
y_pred_svm = svm_classifier.predict(X_test)
print('predict:\n',y_pred_svm)
print(classification_report(y_test,y_pred_svm))

# tính accuracy 
acc_score_svm = metrics.accuracy_score(y_pred_svm,y_test) 
print('accuracy:\n',acc_score_svm) 

predict:
 [0 0 0 ... 0 0 0]
              precision    recall  f1-score   support

           0       0.41      1.00      0.58      4286
           1       0.00      0.00      0.00         5
           2       0.00      0.00      0.00       103
           3       0.00      0.00      0.00       353
           4       0.00      0.00      0.00      1095
           5       0.00      0.00      0.00      1962
           6       0.00      0.00      0.00       447
           7       0.00      0.00      0.00       520
           8       0.00      0.00      0.00       832
           9       0.00      0.00      0.00        45
          10       0.00      0.00      0.00       522
          11       0.00      0.00      0.00       267

    accuracy                           0.41     10437
   macro avg       0.03      0.08      0.05     10437
weighted avg       0.17      0.41      0.24     10437

accuracy:
 0.41065440260611286


//anaconda3/envs/nlp/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
