In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [3]:
X = np.array([[1,2,3,4,5,6,7],[1.5,2.5,3.5,4.5,5.5,6.5,7.5]])
Y = np.array([[2,4,6,8,10,12,14]])
print(X.shape)
one = np.ones((X.shape[1], 1))
X = np.array(X).T
X = np.concatenate((one,X),axis=1)
Y = np.array(Y).T

# test 
print(X)
W = np.array([[1,1,2]]).T
print(W)
c = np.dot(X,W)
print(c)

(2, 7)
[[1.  1.  1.5]
 [1.  2.  2.5]
 [1.  3.  3.5]
 [1.  4.  4.5]
 [1.  5.  5.5]
 [1.  6.  6.5]
 [1.  7.  7.5]]
[[1]
 [1]
 [2]]
[[ 5.]
 [ 8.]
 [11.]
 [14.]
 [17.]
 [20.]
 [23.]]


In [4]:
# step 1: initialize and forward propagate  
# y = w_1 * x + w_0
def f(x):
    return np.dot(x,W) 
print(X[2])
print(W)
print(f(X[2])) 
#print(len(X))

[1.  3.  3.5]
[[1]
 [1]
 [2]]
[11.]


In [5]:
# step 2: loss function 
def loss():
    sum = 0
    for i in range(len(X)):
        sum += (f(X[i])-Y[i])**2
    return sum/(2*len(X)) 
print(loss())

[20.]


In [6]:
# step 3: Differentiation
def derivate(k):
    sum = 0
    for i in range(len(X)):
        sum += 2*(f(X[i])-Y[i])*X[i][k]
    return sum/(2*len(X))

print(derivate(1))
print(derivate(0))

[28.]
[6.]


In [9]:
# step 4: update weight 
epoch = 50
learning_rate = 0.01
epsilon = 0.01
W = np.array([[1,3.5,5]]).T
for iter in range(epoch):
    before_loss = loss()
    print(iter,': ',before_loss) 
    for k in range(len(W)):
        W[k] = W[k] - learning_rate*derivate(k)
    if before_loss-loss() < epsilon:
        break 
# print result 
print('W:')
print(W)
    

0 :  [519.625]
1 :  [187.87304052]
2 :  [67.98154851]
3 :  [24.65452143]
4 :  [8.99693778]
5 :  [3.33858773]
6 :  [1.29368419]
7 :  [0.55452384]
8 :  [0.2871691]
9 :  [0.19027266]
10 :  [0.1549495]
11 :  [0.14186143]
W:
[[ 0.24127331]
 [-0.06458249]
 [ 1.84405594]]
